services:
  traefik:
    image: traefik:v3.3
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=e2e_traefik
      - '--entrypoints.web.address=:80'
    ports:
      - '9080:80'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    networks:
      - traefik

  registry:
    image: registry:2
    ports:
      - '5001:5000'
    networks:
      - traefik

networks:
  traefik:
    name: e2e_traefik
